apiVersion: v2
name: demo-app
description: Demo application for k8s ephemeral PR environments
type: application
version: 0.2.0
appVersion: "1.0.0"
kubeVersion: ">=1.25.0-0"

keywords:
  - demo
  - ephemeral
  - pr-environment

home: https://github.com/genesluna/k8s-ephemeral-environments
sources:
  - https://github.com/genesluna/k8s-ephemeral-environments

maintainers:
  - name: genesluna

dependencies:
  - name: k8s-ee-postgresql
    alias: postgresql
    version: "1.1.0"
    repository: "file://../postgresql"
    condition: postgresql.enabled
  - name: k8s-ee-mongodb
    alias: mongodb
    version: "1.1.0"
    repository: "file://../mongodb"
    condition: mongodb.enabled
  - name: k8s-ee-redis
    alias: redis
    version: "1.1.0"
    repository: "file://../redis"
    condition: redis.enabled
  - name: k8s-ee-minio
    alias: minio
    version: "1.1.0"
    repository: "file://../minio"
    condition: minio.enabled
  - name: k8s-ee-mariadb
    alias: mariadb
    version: "1.0.0"
    repository: "file://../mariadb"
    condition: mariadb.enabled
