apiVersion: v2
name: k8s-ee-app
description: Generic application chart for k8s ephemeral PR environments
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.25.0-0"

keywords:
  - generic
  - application
  - ephemeral
  - pr-environment

home: https://github.com/koder-cat/k8s-ephemeral-environments
sources:
  - https://github.com/koder-cat/k8s-ephemeral-environments

maintainers:
  - name: k8s-ee-platform

dependencies:
  - name: k8s-ee-postgresql
    alias: postgresql
    version: "1.1.0"
    repository: "oci://ghcr.io/koder-cat/k8s-ephemeral-environments/charts"
    condition: postgresql.enabled
  - name: k8s-ee-mongodb
    alias: mongodb
    version: "1.1.0"
    repository: "oci://ghcr.io/koder-cat/k8s-ephemeral-environments/charts"
    condition: mongodb.enabled
  - name: k8s-ee-redis
    alias: redis
    version: "1.1.0"
    repository: "oci://ghcr.io/koder-cat/k8s-ephemeral-environments/charts"
    condition: redis.enabled
  - name: k8s-ee-minio
    alias: minio
    version: "1.1.0"
    repository: "oci://ghcr.io/koder-cat/k8s-ephemeral-environments/charts"
    condition: minio.enabled
  - name: k8s-ee-mariadb
    alias: mariadb
    version: "1.0.0"
    repository: "oci://ghcr.io/koder-cat/k8s-ephemeral-environments/charts"
    condition: mariadb.enabled
